### ISSUE TITLE
Error: getaddrinfo ENOTFOUND in travis

### ISSUE THREAD

**Issue by phi4grv** [parti-xyz/auth-ui#31]
```
Error: getaddrinfo ENOTFOUND auth-api auth-api:3030
  at errnoException (dns.js:26:10)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

**Comment by phi4grv** [comment]
양방향 컨터이너 링크때문에 생기는 문제이다.
여러가지 해결 방법이 있는데 아래 두가지 방식을 사용했다.
- https://github.com/parti-xyz/add-host-to-docker
- 도커 컴포저 파일 버전 2
